PT-1924: Add rounding policy
VirtoCommerce/vc-module-core pull request #189
Opened 2021-07-28 12:46 UTC by krankenbro

## Description

## References
### QA-test: PT-1927
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-1924
### Artifact URL:

2021-07-28 12:55 UTC, Vectorfield4 commented
Write Unit-tests for `DefaultMoneyRoundingPolicy`

2021-07-28 13:48 UTC, tatarincev requested changes

2021-07-28 13:48 UTC, tatarincev commented on src/VirtoCommerce.CoreModule.Core/Currency/Currency.cs
> +        public IMoneyRoundingPolicy RoundingPolicy { get; set; }
Please add [JsonIgnore] attribute

2021-07-28 13:48 UTC, tatarincev commented on src/VirtoCommerce.CoreModule.Core/Currency/RoundingType.cs
> +    public enum RoundingType
add comment please //Cash rounding (details: https://en.wikipedia.org/wiki/Cash_rounding)

2021-07-28 13:48 UTC, tatarincev commented on src/VirtoCommerce.CoreModule.Data/Currency/CurrencyService.cs
> +            _moneyRoundingPolicy = moneyRoundingPolicy;
Missed  `_moneyRoundingPolicy` initialization  to returned currencies from the service

2021-07-30 17:51 UTC, Vectorfield4 approved these changes
You can merge this PR after fixing code smells.

2021-08-05 09:21 UTC, merged